//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_AID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int id { get; set; }
        public string admin_fname { get; set; }
        public string admin_lname { get; set; }
        public string admin_email { get; set; }
        public string admin_password { get; set; }
    }
}
