//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_AID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONATIONS
    {
        public int id { get; set; }
        public System.DateTime donation_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> cause_id { get; set; }
        public Nullable<int> donation_amount { get; set; }
    
        public virtual CAUSES CAUSES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
