//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_AID.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACKS
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string feedback_msg { get; set; }
        public System.DateTime feedback_date { get; set; }
        [JsonIgnore]
        public virtual USERS USERS { get; set; }
    }
}
