//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_AID.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY
    {
        public int id { get; set; }
        public string image_url { get; set; }
        public Nullable<int> event_id { get; set; }
        [JsonIgnore]
        public virtual EVENTS EVENTS { get; set; }
    }
}
