//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_AID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiveAIDdbEntities : DbContext
    {
        public GiveAIDdbEntities()
            : base("name=GiveAIDdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMIN { get; set; }
        public virtual DbSet<CAUSES> CAUSES { get; set; }
        public virtual DbSet<DONATIONS> DONATIONS { get; set; }
        public virtual DbSet<EVENTS> EVENTS { get; set; }
        public virtual DbSet<FEEDBACKS> FEEDBACKS { get; set; }
        public virtual DbSet<GALLERY> GALLERY { get; set; }
        public virtual DbSet<JOBS> JOBS { get; set; }
        public virtual DbSet<PARTNERS> PARTNERS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
